### PR TITLE
Stuff needed for compatibility with Castle

### PR DESCRIPTION
**Pull request by lars-erik**

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Finally found some time to review. Lots of questions ;-)

A. Why do we need component initializers? I can see how they work, I'm sorta happy having them, but ... is there a reason apart from "cleaner"? Also, would you oppose getting rid of the property which returns the type, to be replaced by a `[ComponentInitializer(typeof(Whatever))]` attribute? Ah... but reading from previous discussions... you want things to be very visible right? "Screaming architecture"? I understand it, yet I'd like to keep things as simple to implement as possible. Discuss.

A(2). On twitter you do mention "dropping the Type property" and have (if I understand) have the `Compose()` method register the initializer... but then how do you find out which initializer to run? You *could* get them all from the container, but they need to run in the same order as components. So?

B. Reason for naming parameters in `CreateInstance`? Cannot remember.

C. So we seem to have a general problem with re-registration. It somehow works with LightInject, although I had to trick it in some places. It seems to be complex to get it to work with Castle. But I don't like that we impose that services be named in order to deal with it. And I don't like that we seem to make everything more complex, just to deal with it. Or maybe we could decide that *every* singleton service is registered as named, using the service name as a name? So `RegisterSingleton<IService, Implementation>()` would name it "Namespace.IService"? And make it the default?

C(2). You mentioned, somewhere, a double `UmbracoContext` registration (one singleton, on transient) - that should not happen, need to fix. See your comments, I need to clean things up. And *ideally* we don't inject `UmbracoContext` ever, but the accessor.

D. `IContainer.Release()` - where is it used? Ah, in the controller factories, which have been fixed to properly release controllers, is that right?

E. You seem to have restored `container.RegisterInstance(container)` can't we avoid it? Smells?

F. Need more work on filesystems, don't like that we have to go back to `Activator` and cannot user the container to initialize the media filesystem. I can look into it.

So... before all this can be merged, I think C (re-registration) needs to be fixed, it's really blocking. Then, all the rest of course, but they are less critical. Let's discuss it.

**Comment by lars-erik** [comment]
A. Yes, the initializers are a lot cleaner. I'm not happy with exposing the type as a property although it screams. Attribute is feasible and almost doesn't smell. :P Possibly ICompositionWithInitializer would scream more? Will give it a bit more thought.

A2. When initializers run all the compositions will have been composed. Why would they need to run in the same order? Is there something that must be initialized first? Sounds a bit like another form of temporal coupling. Initialization should be "per module", ie. not dependent on other modules, right?

B. Let's run with the dictionary. Just a compatibility thing. (If we're on the same CreateInstance)

C. It was actually easily solved. In Castle's case the problem is only with factory registrations. Other registrations just add to what you'd get with GetInstances<T>. By default, the first registered is the one you get when you call GetInstance<T>. The same goes for singletons, but in the castle adapter, I've configured singletons as "default" when they're registered. This means for _umbraco_, the last registered singleton will be the one you get from GetInstance<T>. The factory problem was solved by implicitly naming registrations "TServiceName-factory-[new guid]". I didn't write a test to see how LI does it yet, but I aspire to do that in the containers repo.

D. Yep. :)

E. Can't remove it. It's being used for the factory methods. Since it's our abstraction (IContainer), it's the only way the container can know about it when passing it to factory methods.

F. Yes. I think I should re-visit the initial commit tho, due to C. But there's still a lot of weirdness around those. I still don't _really_ know what a shadow-wrapper does. :D 

So now we basically need to decide what _should_ be defaults. (C)
Then maybe revert the overrides I added.
Re-visit F.
Think about A.

Side note:
I was hoping to run all the Umbraco tests with Castle in that other repo, but they blow up due to Castle not wanting target-less proxies (mocks) as instances from factories. There are 1744 tests failing due to this. I managed to get the ImageCropperTest.CanConvertImage.... test to pass by changing the registrations to .RegisterInstance(). However it's an impossible rule to impose on the core, so I'll just cross my fingers waiting for Moq 5. It supposedly doesn't use Castle.Core.DynamicProxy. Never-the-less, I can't shake the feeling that that factory registration support opens up abuse where one really should've registered instances with RegisterInstace. Thoughts?

PS. Upgrading blows up with Castle due to scope not having been created in a getscope call. Works with LI. My adapter does it wrong? Gotta research more. Ideas appreciated.

PPS. API Controllers aren't instantiated using the container w/LI. With Castle it complains it hasn't been registered.

**Comment by lars-erik** [comment]
Barely got started with a controller showing all registrations. We can add some indicators if lesser scopes are in bigger ones. I think there are a few shady cases. ;)

image

**Comment by lars-erik** [comment]
I've been getting things up and running again. Reg. the PPS, had to register external controllers. I guess that's fine. That's why we have compositions. :)

After fiddling around a bit more, I think we should go ahead and merge all the way.
Any improvements from here can be done as smaller pull requests with more focused effort.
IE. initializers, named services, file systems etc.

Just gonna see if I can find the last few overrides I made to work around the default stuff.

Doubts?

**Comment by lars-erik** [comment]
Well, I found my own doubts, and well founded. That last commit there breaks it because it uses another form and default. So back to C:

I wrote a couple of tests in my containers repo now and ran them with both containers respectively.
Just two simple tests show two distinct differences.
They use the Register(Type, Type, Lifetime) overload.

1. Transients
- LightInject can't decide the first or last if they're not named. So if you resolve an abstraction that has two concretes it blows up.
- Castle gives you the first one you registered.
2. Singletons
- Lightinject happily makes the last registered default (IE. active)
- Castle makes the first registered default

I think the fact that either might find it proper to throw up is a risk and bigger burden than noobs should be exposed to. It would be nice if we found some common ground or just a rule per lifetime that has to be implemented in each provider.
IE. first/last _will_ be the default for this lifetime and this or that multiplicity means you have to name the services.
We could go on fleshing out my tests to make some decision. It can be found here:  
https://github.com/lars-erik/our.umbraco.containers/blob/master/Our.Umbraco.Containers.Castle.UmbracoTests/Defaults/Defaults.cs

Once that's sorted, I can revert the last couple of overrides I made.

This is probably not blocking though. Not sure how much we're risking wrt. delaying merging.

**Comment by lars-erik** [comment]
Fleshing out those tests. I guess the best path for now is to require that other components "behave" like LI as far as it's possible. I'll see how far I get.

**Comment by lars-erik** [comment]
I'm completely baffled. Here's the facts with LightInject. Apparently LightInject just throws away old registrations for anything but transients. When resolving from multiple (transient) registrations for one abstration, you have to name the one your after.  
I'll verify it, but I'd be amazed if we can't have multiple named components with the other lifetimes.

   Multiple_Type_Without_Service_Is_Irrelevant [0:00.374] Success
   Service_And_Multiple_Instances_Throws_Away_Previous_Instance [0:00.065] Success
   Service_And_Multiple_Type_Removes_Previous_Registration [0:00.007] Success
   Service_And_Multiple_Type_Scoped_Removes_Previous_Registration [0:00.008] Success
   Service_And_Multiple_Type_Singleton_Removes_Previous_Registration [0:00.002] Success
   Service_And_Multiple_Type_Transient_Throws_InvalidOperation [0:00.010] Success

**Comment by lars-erik** [comment]
I guess it's overarching that you cannot have multiple unnamed registrations with LI. I don't really mind.
So it will be up to implementors to chose whether to replicate that, or to support multiple, but make the last registered "default" in all cases. It's just the transient unnamed that is different, and I guess that may be up to implementors as well. Here's an updated fact list:

   Multiple_Type_Without_Service_Is_Irrelevant [0:00.332] Success
   Service_And_Multiple_Factories_Transient_Removes_Previous_Factory [0:00.400] Success
   Service_And_Multiple_Instances_Removes_Previous_Instance [0:00.057] Success
   Service_And_Multiple_Named_Instances_Resolves_Types [0:00.005] Success
   Service_And_Multiple_Named_Type_PerRequest_Resolves_Types [0:00.008] Success
   Service_And_Multiple_Named_Type_Scoped_Resolves_Types [0:00.011] Success
   Service_And_Multiple_Named_Type_Singleton_Resolves_Types [0:00.003] Success
   Service_And_Multiple_Named_Type_Transient_Resolves_Types [0:00.000] Success
   Service_And_Multiple_Type_PerRequest_Removes_Previous_Registration [0:00.001] Success
   Service_And_Multiple_Type_Scoped_Removes_Previous_Registration [0:00.001] Success
   Service_And_Multiple_Type_Singleton_Removes_Previous_Registration [0:00.002] Success
   Service_And_Multiple_Type_Transient_Throws_InvalidOperation [0:00.011] Success

**Comment by lars-erik** [comment]
I've focused in on resolving one unnamed when multiple are registered, for both named and unnamed registrations. Turns out Castle is more forgiving in most cases, and I've been able to configure "last as default" for everything. I now have the following passing tests with *LightInject*:

  LightInject.Resolving_Default_Abstractions_From_Multiple_Registrations (13 tests) [0:00.430] Success
   Factories_Transient_Resolves_Last_Registered [0:00.342] Success
   Instances_Resolves_Last_Registered [0:00.003] Success
   Named_Factories_Transient_Throws_InvalidOperationException [0:00.020] Success
   Named_Instances_Throws_InvalidOperationException [0:00.002] Success
   Named_PerRequest_Throws_InvalidOperationException [0:00.004] Success
   Named_Scoped_Throws_InvalidOperationException [0:00.009] Success
   Named_Transient_Throws_InvalidOperationException [0:00.000] Success
   Named_Type_Singleton_Throws_InvalidOperationException [0:00.002] Success
   PerRequest_Resolves_Last_Registered [0:00.018] Success
   Scoped_Resolves_Last_Registered [0:00.004] Success
   Singleton_Resolves_Last_Registered [0:00.002] Success
   Transient_Throws_InvalidOperation [0:00.000] Success
   Without_Registering_Service_Throws_InvalidOperationException [0:00.001] Success

Castle is more picky about PerRequest, so those fail due to other reasons. But all the others fail because they actually return (I think now, the last) registered component where LI throws.

So I'm not quite sure where to go with this information. Let implementors make sure last is always default and then leave options open where LI would've thrown?

**Comment by lars-erik** [comment]
Tests here:
https://github.com/lars-erik/our.umbraco.containers/blob/master/Our.Umbraco.Containers.Castle.UmbracoTests/Registration/Resolving_Default_Abstractions_From_Multiple_Registrations.cs

**Comment by lars-erik** [comment]
*Poof*, just like that I finally stumbled upon code to overwrite named registrations with Castle > 3.
I'm tempted to say that can be a requirement for containers, then. ><

**Comment by lars-erik** [comment]
Reverting more and more commits. :)

I wanted to check out the MediaFileSystem stuff again. After diving in, I can't help but say that we're trying to do CPR on a hopeless case there. From what I can find we still instantiate the configured FileSystemProvider using reflection. It is then fed to a ShadowWrapper, which is then fed to the concrete MediaFileSystem instance. I can't manage to wrap my head around where Castle makes it a cyclic reference, but the whole setup is daft nonetheless.
I propose we ditch the file configuraiton of filesystem providers. It's a major after all.
Implementors can override the named IFileSystemProvider "MediaFileSystemProvider". Then the base file system provider can have injected services.
Umbraco ships with a default one.
MediaFileSystem doesn't have to go through all the magic and through FileSystems. It can just be registered as a factory as such: c => new MediaFileSystem(new ShadowWrapper(c.Resolve<IFileSystemProvider>("MediaFileSystemProvider")), ...)

It's a lot of code to delete, so I'd like a nod or similar before I chop loose. :D

---

60 min later, I've found CreateInstance in LI. I'd naively implemented it as Resolve in the Castle container. We really have to do something about this.
But should it be another PR?
I think the DI abstraction is fine, it's just the media file system that's bonkers. :D
Don't see any more commits to revert or immediate improvements to be made.

---

Is there a clear case for BootLoader.PrepareComponentTypes2 and surrounding code, or is it something we imagine might be useful? If composition and initialization is separated, why does half of it have to run in order and whatnot? I see something about runtime levels, but there is still magic here I don't understand. Would discovering IRuntimeComponent, IUmbracoCoreComponent and IUmbracoUserComponent respectively help? I'd imagine everything within each group could be composed and initialized in a random order?

**Comment by zpqrtbnk** [comment]
Re. A: the "magic" `Initialize` method works pretty much the same as the ASP.NET Core `Configure` method (see [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#the-configure-method)) - and, having to return the initializer type via a property is not pretty, but anything else (attribute, generic parameter...) makes it less obvious again. So... I _think_ I'm about to decide to stick with the `Initialize` method and kill initializers. Not done yet, but almost.

Re. B: ok, does not hurt, let's use the dictionary.

Re. others: need time ;-)

**Comment by lars-erik** [comment]
How 'bout just having compositions register initializers and that's that? :)

I really need a walkthrough of all the compose/initialize code and why it's so elaborate. Can't shake the feeling you could make that an order of magnitude more simple.

**Pull request merged**
